version: '3.8'
services:
    # TODO: include nginx container
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # 'host=0.0.0.0' option allows laravel app to be accessible from outside of container
        command: >
          sh -c 'php artisan migrate --seed &&
                 php artisan storage:link &&
                 php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            db:
              condition: service_healthy

    db: # inside .env, define DB_HOST=db
        platform: linux/x86_64
        image: mysql:5.7.16
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            # MYSQL_USER:
            # MYSQL_PASSWORD:
            # MYSQL_ROOT_PASSWORD:
        volumes:
            - ./storage/dbdata:/var/lib/mysql # first time running docker-compose
                                              # dbdata must be empty
        ports:
            - 3306:3306
        healthcheck:
          test: mysqladmin ping -h localhost
          timeout: 20s
          retries: 10
